### ISSUE TITLE
Build it report fails on a fresh new CDM 5.2.0 system 

### ISSUE THREAD

**Issue by GideonSwheeler** [AsBuiltReport/AsBuiltReport.Rubrik.CDM#9]
Powershell version 5
Rubrik Latest
AsBuiltReport Latest

VERBOSE: [ 23:33:02:507 ] [ Document ] - Document 'Rubrik As Built Report - 2020-07-30_23.32.45' processing completed.
VERBOSE: [ 23:33:02:512 ] [ Document ] - Total processing time '17.32' seconds.
N
New-AsBuiltReport : The property 'Value' cannot be found on this object. Verify that the property exists.
At line:1 char:1
+ New-AsBuiltReport -Target 10.46.120.4 -Report Rubrik.CDM -Format Word ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

No Word or HTML file is generated

**Comment by mwpreston** [comment]
This should be resolved in PR #7

**Comment by intermittech** [comment]
I am seemingly still running into this issue. I have 2 rubrik clusters, one the script (v1 from Master) runs fine and outputs the word document but on the other I get the same error as @GideonSwheeler posted.

I've tried installing the -DEV version and the modules reports in powershell it's the v5.2 version, but I still get the same error?

The first cluster does have more things configured already then the second cluster but I have no clue which value the script is missing to complete.

Both are running version: 5.2.2-p5-9962

Any help would be appreciated! :)
